-- V34 (2026-09-17): Kingdee voucher rule engine — data model foundation (WP-A)
--
-- Design source: docs/kingdee-openapi/voucher-rule-engine-20260916.md (v1) +
--   docs/kingdee-openapi/voucher-rules-seed-20260916.json (22 rules from finance team).
-- Bank statement -> GL_VOUCHER rule engine: rules are matched against APPROVED statements
-- (priority ascending), producing debit/credit line templates with dimension sources
-- (BANK_ACCOUNT/ORG/EMPLOYEE/SUPPLIER/CUSTOMER/COUNTERPARTY/FIXED/BY_SUMMARY_BRANCH/NONE)
-- and amount sharing strategies (FULL/EQUAL/MANUAL).
--
-- Data model notes:
--   rule_no           business rule number from the finance mapping sheet (1..22), stable id
--   scope_orgs        FINFLOW company scope, comma-separated org codes (300/400/710/720/900), ALL = any
--   scope_bank_channels comma-separated CITIC/CMB, empty string = any channel
--   match_json        full match object: {logic: ALL|ANY, conditions: [{field, op, values}]};
--                     extra annotation keys (amountGate/note) are documentation-only, ignored by the matcher
--   debit/credit_lines_json line template arrays [{account, name, dimension, value?, branches?, share}]
--   extra_voucher_json second-voucher template (direct expense confirmation), rules 1 and 14
--   amount_min/max    reserved amount gate (social insurance vs income tax threshold, pending finance input)
--   enabled           soft switch; disabled rules are skipped by the matcher
--
-- Seed import: 22 rows verbatim from the finance sheet. Later rule additions go through
-- new migrations (append-only INSERTs) until a rule-maintenance UI exists.

CREATE TABLE kingdee_voucher_rule (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    rule_no INT NOT NULL,
    business_type VARCHAR(64) NOT NULL,
    category VARCHAR(32) NOT NULL,
    priority INT NOT NULL,
    scope_orgs VARCHAR(255) NOT NULL,
    scope_bank_channels VARCHAR(64) NOT NULL,
    direction VARCHAR(8) NOT NULL,
    amount_min DECIMAL(18,2) NULL,
    amount_max DECIMAL(18,2) NULL,
    match_json VARCHAR(2000) NOT NULL,
    debit_lines_json VARCHAR(4000) NOT NULL,
    credit_lines_json VARCHAR(2000) NOT NULL,
    extra_voucher_json VARCHAR(4000) NULL,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    remark VARCHAR(1000) NULL,
    created_at TIMESTAMP NULL DEFAULT NULL,
    updated_at TIMESTAMP NULL DEFAULT NULL,
    CONSTRAINT uk_kingdee_voucher_rule_no UNIQUE (rule_no)
);

CREATE INDEX idx_kvr_priority_enabled ON kingdee_voucher_rule (enabled, priority);

-- ---- seed: 22 rules verbatim from finance sheet (2026-09-16) ----

INSERT INTO kingdee_voucher_rule (rule_no, business_type, category, priority, scope_orgs, scope_bank_channels, direction, amount_min, amount_max, match_json, debit_lines_json, credit_lines_json, extra_voucher_json, enabled, remark, created_at, updated_at) VALUES (1, '即时行乐报销', '费用类', 20, '300', 'CITIC', 'EXPENSE', NULL, NULL, '{"logic":"ALL","conditions":[{"field":"SUMMARY","op":"CONTAINS","values":["报销"]},{"field":"COUNTERPARTY_NAME","op":"EMPLOYEE_NAME","values":[]}]}', '[{"account":"2241.04","name":"其他应付款_员工往来","dimension":"FIXED","value":"部门=1001/项目=即时行乐","share":"FULL"}]', '[{"account":"1002","name":"银行存款","dimension":"BANK_ACCOUNT","share":"FULL"}]', '{"note":"直接确认费用（第二张凭证）","debitLines":[{"account":"6602.11","name":"管理费用_福利费","dimension":"FIXED","value":"部门=综合管理部；项目=即时行乐","share":"FULL"}],"creditLines":[{"account":"2241.04","name":"其他应付款_员工往来","dimension":"EMPLOYEE","share":"FULL"}]}', 1, '主体银行=即设中信；识别=员工个人名字；维度列原文「1001/即时行乐」', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO kingdee_voucher_rule (rule_no, business_type, category, priority, scope_orgs, scope_bank_channels, direction, amount_min, amount_max, match_json, debit_lines_json, credit_lines_json, extra_voucher_json, enabled, remark, created_at, updated_at) VALUES (2, '集团主体往来', '往来类', 30, 'ALL', '', 'ANY', NULL, NULL, '{"logic":"ALL","conditions":[{"field":"COUNTERPARTY_NAME","op":"IN_ORG_LIST","values":["ORG_NAMES"]}]}', '[{"account":"2241.05","name":"其他应付款_内部往来","dimension":"ORG","share":"FULL"}]', '[{"account":"1002","name":"银行存款","dimension":"BANK_ACCOUNT","share":"FULL"}]', NULL, 1, '主体银行=所有主体；识别=对手方为集团内部主体；维度=组织机构。收入方向（收到内部往来款）借贷对调：借1002/贷2241.05', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO kingdee_voucher_rule (rule_no, business_type, category, priority, scope_orgs, scope_bank_channels, direction, amount_min, amount_max, match_json, debit_lines_json, credit_lines_json, extra_voucher_json, enabled, remark, created_at, updated_at) VALUES (3, '备款到薪福通', '往来类', 25, '300,400,710,720', 'CMB', 'ANY', NULL, NULL, '{"logic":"ALL","conditions":[{"field":"COUNTERPARTY_NAME","op":"CONTAINS","values":["招商银行","应付代发业务清算款"]}]}', '[{"account":"1002","name":"银行存款","dimension":"BANK_ACCOUNT","share":"FULL"}]', '[{"account":"1002","name":"银行存款","dimension":"BANK_ACCOUNT","value":"对方账户=该主体薪福通账户映射","share":"FULL"}]', NULL, 1, '主体银行=即设、雪云、长沙、广州；维度=各主体对应的薪福通账号（银行↔银行内部划转，依赖账户映射表）', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO kingdee_voucher_rule (rule_no, business_type, category, priority, scope_orgs, scope_bank_channels, direction, amount_min, amount_max, match_json, debit_lines_json, credit_lines_json, extra_voucher_json, enabled, remark, created_at, updated_at) VALUES (4, '购买理财/结构性存款', '理财类', 20, '300', 'CITIC', 'EXPENSE', NULL, NULL, '{"logic":"ALL","conditions":[{"field":"SUMMARY","op":"CONTAINS","values":["购买理财","结构性存款"]}]}', '[{"account":"1101.01","name":"交易性金融资产_成本","dimension":"NONE","share":"FULL"}]', '[{"account":"1002","name":"银行存款","dimension":"BANK_ACCOUNT","share":"FULL"}]', NULL, 1, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO kingdee_voucher_rule (rule_no, business_type, category, priority, scope_orgs, scope_bank_channels, direction, amount_min, amount_max, match_json, debit_lines_json, credit_lines_json, extra_voucher_json, enabled, remark, created_at, updated_at) VALUES (5, '员工借款', '借款类', 20, '300', 'CITIC', 'EXPENSE', NULL, NULL, '{"logic":"ALL","conditions":[{"field":"SUMMARY","op":"CONTAINS","values":["借款"]}]}', '[{"account":"1221.02","name":"其他应收款_员工借款","dimension":"EMPLOYEE","share":"FULL"}]', '[{"account":"1002","name":"银行存款","dimension":"BANK_ACCOUNT","share":"FULL"}]', NULL, 1, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO kingdee_voucher_rule (rule_no, business_type, category, priority, scope_orgs, scope_bank_channels, direction, amount_min, amount_max, match_json, debit_lines_json, credit_lines_json, extra_voucher_json, enabled, remark, created_at, updated_at) VALUES (6, '支付银行手续费', '费用类', 20, '300,400', 'CITIC', 'EXPENSE', NULL, NULL, '{"logic":"ALL","conditions":[{"field":"SUMMARY","op":"CONTAINS","values":["手续费","银行服务费","银行收费"]}]}', '[{"account":"6603.04","name":"财务费用_手续费","dimension":"NONE","share":"FULL"}]', '[{"account":"1002","name":"银行存款","dimension":"BANK_ACCOUNT","share":"FULL"}]', NULL, 1, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO kingdee_voucher_rule (rule_no, business_type, category, priority, scope_orgs, scope_bank_channels, direction, amount_min, amount_max, match_json, debit_lines_json, credit_lines_json, extra_voucher_json, enabled, remark, created_at, updated_at) VALUES (7, 'API用量采购', '预付类', 20, '300,400', 'CITIC', 'EXPENSE', NULL, NULL, '{"logic":"ALL","conditions":[{"field":"SUMMARY","op":"CONTAINS","values":["API用量采购"]}]}', '[{"account":"1123.01","name":"预付账款_外部往来","dimension":"SUPPLIER","value":"项目=图虫","share":"FULL"}]', '[{"account":"1002","name":"银行存款","dimension":"BANK_ACCOUNT","share":"FULL"}]', NULL, 1, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO kingdee_voucher_rule (rule_no, business_type, category, priority, scope_orgs, scope_bank_channels, direction, amount_min, amount_max, match_json, debit_lines_json, credit_lines_json, extra_voucher_json, enabled, remark, created_at, updated_at) VALUES (8, '支付房租', '预付类', 20, '300,710,720', 'CITIC,CMB', 'EXPENSE', NULL, NULL, '{"logic":"ALL","conditions":[{"field":"SUMMARY","op":"CONTAINS","values":["租金","房租"]},{"field":"COUNTERPARTY_NAME","op":"CONTAINS_ANY","values":["北京柏豪置业","长沙中电产业园","天银科创"]}]}', '[{"account":"2601.01","name":"租赁负债_租赁付款额","dimension":"SUPPLIER","share":"FULL"}]', '[{"account":"1002","name":"银行存款","dimension":"BANK_ACCOUNT","share":"FULL"}]', NULL, 1, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO kingdee_voucher_rule (rule_no, business_type, category, priority, scope_orgs, scope_bank_channels, direction, amount_min, amount_max, match_json, debit_lines_json, credit_lines_json, extra_voucher_json, enabled, remark, created_at, updated_at) VALUES (9, '支付物业', '预付类', 20, '300,710', 'CITIC,CMB', 'EXPENSE', NULL, NULL, '{"logic":"ALL","conditions":[{"field":"SUMMARY","op":"CONTAINS","values":["物业"]},{"field":"COUNTERPARTY_NAME","op":"CONTAINS","values":["北京柏豪达美物业"]}]}', '[{"account":"2241.06","name":"其他应付款_外部往来","dimension":"SUPPLIER","share":"FULL"}]', '[{"account":"1002","name":"银行存款","dimension":"BANK_ACCOUNT","share":"FULL"}]', NULL, 1, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO kingdee_voucher_rule (rule_no, business_type, category, priority, scope_orgs, scope_bank_channels, direction, amount_min, amount_max, match_json, debit_lines_json, credit_lines_json, extra_voucher_json, enabled, remark, created_at, updated_at) VALUES (10, '缴纳社保（金额大）', '五险一金', 15, '300,400,900', 'CITIC', 'EXPENSE', NULL, NULL, '{"logic":"ALL","conditions":[{"field":"SUMMARY","op":"CONTAINS","values":["扣国地税"]}],"amountGate":"与规则11同附言，靠金额区分：社保=金额大。阈值待财务提供，落地前两条均进人工确认队列"}', '[{"account":"2241.02.01","name":"其他应付款_社保_养老","dimension":"NONE","share":"MANUAL"},{"account":"2241.02.03","name":"其他应付款_社保_医疗","dimension":"NONE","share":"MANUAL"},{"account":"2241.02.02","name":"其他应付款_社保_失业","dimension":"NONE","share":"MANUAL"},{"account":"2211.02.01","name":"应付职工薪酬_社保_养老","dimension":"NONE","share":"MANUAL"},{"account":"2211.02.05","name":"应付职工薪酬_社保_医疗","dimension":"NONE","share":"MANUAL"},{"account":"2211.02.02","name":"应付职工薪酬_社保_失业","dimension":"NONE","share":"MANUAL"},{"account":"2211.02.03","name":"应付职工薪酬_社保_工伤","dimension":"NONE","share":"MANUAL"},{"account":"2211.02.04","name":"应付职工薪酬_社保_生育","dimension":"NONE","share":"MANUAL"}]', '[{"account":"1002","name":"银行存款","dimension":"BANK_ACCOUNT","share":"FULL"}]', NULL, 1, '社保各科目录入的金额需要按照上月工资表（人工拆分，8 借方科目）', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO kingdee_voucher_rule (rule_no, business_type, category, priority, scope_orgs, scope_bank_channels, direction, amount_min, amount_max, match_json, debit_lines_json, credit_lines_json, extra_voucher_json, enabled, remark, created_at, updated_at) VALUES (11, '缴纳个税（金额小）', '五险一金', 15, '300', 'CITIC', 'EXPENSE', NULL, NULL, '{"logic":"ALL","conditions":[{"field":"SUMMARY","op":"CONTAINS","values":["扣国地税"]}],"amountGate":"个税=金额小；阈值待财务提供"}', '[{"account":"2221.06","name":"应交税费_代扣个人所得税","dimension":"NONE","share":"FULL"}]', '[{"account":"1002","name":"银行存款","dimension":"BANK_ACCOUNT","share":"FULL"}]', NULL, 1, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO kingdee_voucher_rule (rule_no, business_type, category, priority, scope_orgs, scope_bank_channels, direction, amount_min, amount_max, match_json, debit_lines_json, credit_lines_json, extra_voucher_json, enabled, remark, created_at, updated_at) VALUES (12, '缴纳公积金', '五险一金', 20, '300,710', 'CITIC,CMB', 'EXPENSE', NULL, NULL, '{"logic":"ALL","conditions":[{"field":"COUNTERPARTY_NAME","op":"CONTAINS","values":["住房公积金"]}]}', '[{"account":"2211.03","name":"应付职工薪酬_公积金","dimension":"NONE","share":"EQUAL"},{"account":"2241.03","name":"其他应付款_公积金","dimension":"NONE","share":"EQUAL"}]', '[{"account":"1002","name":"银行存款","dimension":"BANK_ACCOUNT","share":"FULL"}]', NULL, 1, '两个科目金额均分', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO kingdee_voucher_rule (rule_no, business_type, category, priority, scope_orgs, scope_bank_channels, direction, amount_min, amount_max, match_json, debit_lines_json, credit_lines_json, extra_voucher_json, enabled, remark, created_at, updated_at) VALUES (13, '交保证金', '保证金', 20, '300', 'CITIC', 'EXPENSE', NULL, NULL, '{"logic":"ALL","conditions":[{"field":"SUMMARY","op":"CONTAINS","values":["保证金"]}]}', '[{"account":"1221.01","name":"其他应收款_保证金","dimension":"SUPPLIER","share":"FULL"}]', '[{"account":"1002","name":"银行存款","dimension":"BANK_ACCOUNT","share":"FULL"}]', NULL, 1, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO kingdee_voucher_rule (rule_no, business_type, category, priority, scope_orgs, scope_bank_channels, direction, amount_min, amount_max, match_json, debit_lines_json, credit_lines_json, extra_voucher_json, enabled, remark, created_at, updated_at) VALUES (14, '常规对公付款-福利费/办公费', '费用类', 20, '300,400', 'CITIC', 'EXPENSE', NULL, NULL, '{"logic":"ALL","conditions":[{"field":"SUMMARY","op":"CONTAINS","values":["服务费"]}],"note":"业务类型列另提「雪糕饮料、运动」，当前条件仅按表内识别列【服务费】"}', '[{"account":"2241.06","name":"其他应付款_外部往来","dimension":"SUPPLIER","share":"FULL"}]', '[{"account":"1002","name":"银行存款","dimension":"BANK_ACCOUNT","share":"FULL"}]', '{"note":"直接确认费用（第二张凭证）","debitLines":[{"account":"6602.11","name":"管理费用_福利费","dimension":"FIXED","value":"部门=综合管理部；项目=运动福利/日常福利/节日福利（人工选）","share":"MANUAL"},{"account":"6602.02.07.01","name":"管理费用_行政费用_办公费_日常办公费","dimension":"FIXED","value":"部门=综合管理部","share":"MANUAL"}],"creditLines":[{"account":"2241.06","name":"其他应付款_外部往来","dimension":"SUPPLIER","share":"FULL"}]}', 1, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO kingdee_voucher_rule (rule_no, business_type, category, priority, scope_orgs, scope_bank_channels, direction, amount_min, amount_max, match_json, debit_lines_json, credit_lines_json, extra_voucher_json, enabled, remark, created_at, updated_at) VALUES (15, '企业滴滴充值', '其他货币资金', 20, '300', 'CITIC', 'EXPENSE', NULL, NULL, '{"logic":"ALL","conditions":[{"field":"SUMMARY","op":"CONTAINS","values":["滴滴"]}]}', '[{"account":"1012","name":"其他货币资金","dimension":"BANK_ACCOUNT","share":"FULL"}]', '[{"account":"1002","name":"银行存款","dimension":"BANK_ACCOUNT","share":"FULL"}]', NULL, 1, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO kingdee_voucher_rule (rule_no, business_type, category, priority, scope_orgs, scope_bank_channels, direction, amount_min, amount_max, match_json, debit_lines_json, credit_lines_json, extra_voucher_json, enabled, remark, created_at, updated_at) VALUES (16, '灵活用工', '费用类', 20, '400', 'CITIC', 'EXPENSE', NULL, NULL, '{"logic":"ALL","conditions":[{"field":"SUMMARY","op":"CONTAINS","values":["劳务费"]}]}', '[{"account":"2241.06","name":"其他应付款_外部往来","dimension":"SUPPLIER","value":"项目=wegic","share":"FULL"}]', '[{"account":"1002","name":"银行存款","dimension":"BANK_ACCOUNT","share":"FULL"}]', NULL, 1, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO kingdee_voucher_rule (rule_no, business_type, category, priority, scope_orgs, scope_bank_channels, direction, amount_min, amount_max, match_json, debit_lines_json, credit_lines_json, extra_voucher_json, enabled, remark, created_at, updated_at) VALUES (17, '支付服务器费（非腾讯云）', '预付类', 20, '400', 'CITIC', 'EXPENSE', NULL, NULL, '{"logic":"ALL","conditions":[{"field":"SUMMARY","op":"CONTAINS","values":["云服务费"]},{"field":"COUNTERPARTY_NAME","op":"CONTAINS_ANY","values":["阿里云","百度网讯","优刻得"]}]}', '[{"account":"1123.01","name":"预付账款_外部往来","dimension":"SUPPLIER","share":"FULL"}]', '[{"account":"1002","name":"银行存款","dimension":"BANK_ACCOUNT","share":"FULL"}]', NULL, 1, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO kingdee_voucher_rule (rule_no, business_type, category, priority, scope_orgs, scope_bank_channels, direction, amount_min, amount_max, match_json, debit_lines_json, credit_lines_json, extra_voucher_json, enabled, remark, created_at, updated_at) VALUES (18, '支付服务器费（腾讯云）', '预付类', 20, '400', 'CITIC', 'EXPENSE', NULL, NULL, '{"logic":"ALL","conditions":[{"field":"SUMMARY","op":"CONTAINS","values":["云服务费"]},{"field":"COUNTERPARTY_NAME","op":"CONTAINS","values":["腾讯云"]}]}', '[{"account":"2241.06","name":"其他应付款_外部往来","dimension":"BY_SUMMARY_BRANCH","branches":[{"whenSummaryContains":"图虫账号","supplier":"腾讯云计算（北京）有限责任公司-图虫"},{"whenSummaryContains":"即时账号","supplier":"腾讯云计算（北京）有限责任公司-即时"}],"share":"FULL"}]', '[{"account":"1002","name":"银行存款","dimension":"BANK_ACCOUNT","share":"FULL"}]', NULL, 1, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO kingdee_voucher_rule (rule_no, business_type, category, priority, scope_orgs, scope_bank_channels, direction, amount_min, amount_max, match_json, debit_lines_json, credit_lines_json, extra_voucher_json, enabled, remark, created_at, updated_at) VALUES (19, '支付工资', '薪资', 20, '900', 'CITIC', 'EXPENSE', NULL, NULL, '{"logic":"ALL","conditions":[{"field":"SUMMARY","op":"CONTAINS","values":["工资薪金"]}]}', '[{"account":"2211.01","name":"应付职工薪酬_工资","dimension":"NONE","share":"FULL"}]', '[{"account":"1002","name":"银行存款","dimension":"BANK_ACCOUNT","share":"FULL"}]', NULL, 1, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO kingdee_voucher_rule (rule_no, business_type, category, priority, scope_orgs, scope_bank_channels, direction, amount_min, amount_max, match_json, debit_lines_json, credit_lines_json, extra_voucher_json, enabled, remark, created_at, updated_at) VALUES (20, '归还员工借款', '借款类', 20, '300,400', 'CITIC', 'EXPENSE', NULL, NULL, '{"logic":"ALL","conditions":[{"field":"SUMMARY","op":"CONTAINS","values":["归还借款"]}]}', '[{"account":"1002","name":"银行存款","dimension":"BANK_ACCOUNT","share":"FULL"}]', '[{"account":"1221.02","name":"其他应收款_员工借款","dimension":"EMPLOYEE","share":"FULL"}]', NULL, 1, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO kingdee_voucher_rule (rule_no, business_type, category, priority, scope_orgs, scope_bank_channels, direction, amount_min, amount_max, match_json, debit_lines_json, credit_lines_json, extra_voucher_json, enabled, remark, created_at, updated_at) VALUES (21, '对公收入', '收入类', 30, '300,400', 'CITIC', 'INCOME', NULL, NULL, '{"logic":"ANY","conditions":[{"field":"SUMMARY","op":"CONTAINS","values":["收入","转入","打款"]}]}', '[{"account":"1002","name":"银行存款","dimension":"BANK_ACCOUNT","share":"FULL"}]', '[{"account":"1122.01","name":"应收账款_外部往来","dimension":"COUNTERPARTY","share":"FULL"}]', NULL, 1, '附言写【收入、转入、打款】等（宽泛兜底规则，优先级低于精确规则）', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO kingdee_voucher_rule (rule_no, business_type, category, priority, scope_orgs, scope_bank_channels, direction, amount_min, amount_max, match_json, debit_lines_json, credit_lines_json, extra_voucher_json, enabled, remark, created_at, updated_at) VALUES (22, '收到实名验证款', '费用类', 20, '300,400', 'CITIC', 'INCOME', NULL, NULL, '{"logic":"ALL","conditions":[{"field":"SUMMARY","op":"CONTAINS","values":["实名验证"]}]}', '[{"account":"1002","name":"银行存款","dimension":"BANK_ACCOUNT","share":"FULL"}]', '[{"account":"6603.04","name":"财务费用_手续费","dimension":"NONE","share":"FULL"}]', NULL, 1, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
