package com.finance.system.validation;
import com.finance.system.common.api.ApiResponse; import com.finance.system.common.api.PageResponse; import com.finance.system.security.UserPrincipal; import com.finance.system.validation.dto.*; import jakarta.validation.Valid; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/validation") public class ValidationController {
    private final ValidationService service; public ValidationController(ValidationService service){this.service=service;}
    @GetMapping("/rules") @PreAuthorize("hasAnyAuthority('validation:view','validation:manage')") public ApiResponse<PageResponse<ValidationRuleResponse>> rules(@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="20")int size,@RequestParam(required=false)String status,@AuthenticationPrincipal UserPrincipal p){return ApiResponse.success(service.rules(p.getId(),page,size,status));}
    @PostMapping("/rules") @PreAuthorize("hasAuthority('validation:manage')") public ApiResponse<ValidationRuleResponse> rule(@Valid @RequestBody ValidationRuleRequest r,@RequestHeader(value="X-Request-Id",required=false)String requestId,@AuthenticationPrincipal UserPrincipal p){return ApiResponse.success("校验规则草稿已创建",service.createRule(p.getId(),r,requestId));}
    @PostMapping("/rules/{id}/activate") @PreAuthorize("hasAuthority('validation:manage')") public ApiResponse<ValidationRuleResponse> activateRule(@PathVariable Long id,@RequestHeader(value="X-Request-Id",required=false)String requestId,@AuthenticationPrincipal UserPrincipal p){return ApiResponse.success("校验规则已启用",service.activateRule(p.getId(),id,requestId));}
    @GetMapping("/mappings") @PreAuthorize("hasAnyAuthority('validation:view','validation:manage')") public ApiResponse<PageResponse<AccountingMappingResponse>> mappings(@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="20")int size,@RequestParam(required=false)String status,@AuthenticationPrincipal UserPrincipal p){return ApiResponse.success(service.mappings(p.getId(),page,size,status));}
    @PostMapping("/mappings") @PreAuthorize("hasAuthority('validation:manage')") public ApiResponse<AccountingMappingResponse> mapping(@Valid @RequestBody AccountingMappingRequest r,@RequestHeader(value="X-Request-Id",required=false)String requestId,@AuthenticationPrincipal UserPrincipal p){return ApiResponse.success("入账映射草稿已创建",service.createMapping(p.getId(),r,requestId));}
    @PostMapping("/mappings/{id}/activate") @PreAuthorize("hasAuthority('validation:manage')") public ApiResponse<AccountingMappingResponse> activateMapping(@PathVariable Long id,@RequestHeader(value="X-Request-Id",required=false)String requestId,@AuthenticationPrincipal UserPrincipal p){return ApiResponse.success("入账映射已启用",service.activateMapping(p.getId(),id,requestId));}
}
