spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:finance;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.finance.system: INFO
    org.springframework.security: INFO
